### ISSUE TITLE
Please relase a new version

### ISSUE THREAD

**Issue by Kixunil** [Stebalien/term#106]
The old version depends on `dirs` which is not maintained and causes transitive dependency on an old `cfg_if` leading to duplication. Releasing a new version would fix these issues.

**Comment by Stebalien** [comment]
In progress.

**Comment by Stebalien** [comment]
Done. I've released 0.7 as this version technically bumps the minimum rust version due to updated error trait usage.

**Comment by Kixunil** [comment]
Awesome, thanks a lot!
