### ISSUE TITLE
Switch winapi dependency to windows/windows-sys

### ISSUE THREAD

**Issue by atouchet** [Stebalien/term#114]
The winapi crate is no longer maintained and there are now official windows/windows-sys crates from Microsoft. term should transition from using winapi to windows/windows-sys.

**Comment by Stebalien** [comment]
@atouchet I've fixed this, but I don't have the ability to test it beyond running the windows tests in CI. Can you validate that the latest commit on master works on Windows before I cut a release?

**Comment by Stebalien** [comment]
Well, the tests pass so I'm going to assume it works (mostly mechanical changes so it should).

**Comment by Stebalien** [comment]
(I've cut a 1.0 release)

**Comment by cole-h** [comment]
@Stebalien Sorry to necro this thread, but could you also tag the 1.0.0 release commit as such? Right now, there are only tags for up to 0.7.0 on GitHub. Thanks!

**Comment by Stebalien** [comment]
Tagged.

**Comment by cole-h** [comment]
Thanks a ton!!!
