### ISSUE TITLE
terminfo testing

### ISSUE THREAD

**Issue by steveklabnik** [Stebalien/term#12]
<a href="https://github.com/cmr"><img src="https://avatars.githubusercontent.com/u/704250?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cmr](https://github.com/cmr)**
_Saturday Jun 01, 2013 at 00:01 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/6870_

_This issue was labelled with: A-testsuite, E-easy in the Rust repository_

----

extra::terminfo testing needs to be more thorough and especially we need to distribute some terminfo entries in src/test and verify that all the expected capabilities are there and their correct values.

**Comment by Stebalien** [comment]
Fixed
