### ISSUE TITLE
`get_dbpath_for_term` handles `~/.terminfo` incorrectly

### ISSUE THREAD

**Issue by lilyball** [Stebalien/term#121]
NOT A CONTRIBUTION

The `get_dbpath_for_term` function falls back to checking `~/.terminfo` only if the `TERMINFO_DIRS` env var is unset. This does not match ncurses logic. According to the `terminfo(5)` manpage (and matching observed behavior of `infocmp`) the correct logic here is to check `~/.terminfo` if the `TERMINFO` env var is unset.

What's more, it's also documented as checking the compiled-in directory list and system terminfo directory (`/usr/share/terminfo`) unconditionally but this library only checks those locations if `TERMINFO_DIRS` is unset.

This is a problem for me because I copied a terminfo file to a remote server using `infocmp -x | ssh machine -- tic -x -`, which placed it in `~/.terminfo`, and now programs that use ncurses work fine but programs that use this crate don't. In particular, [skim](https://github.com/skim-rs/skim) is very broken.

**Comment by Stebalien** [comment]
Fixed in v1.0.1.
