### ISSUE TITLE
term: windows console handling is incomplete

### ISSUE THREAD

**Issue by steveklabnik** [Stebalien/term#13]
<a href="https://github.com/cmr"><img src="https://avatars.githubusercontent.com/u/704250?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cmr](https://github.com/cmr)**
_Tuesday Apr 08, 2014 at 14:55 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/13400_

_This issue was labelled with: A-libs, A-windows, E-easy in the Rust repository_

----

The [Windows Console API](http://msdn.microsoft.com/en-us/library/windows/desktop/ms682073%28v=vs.85%29.aspx) is large and complex. libterm only handles using stdout as a console.

Honestly nobody cares about the windows console API. This work probably belongs in https://github.com/klutzy/rust-windows

**Comment by cmr** [comment]
These days, I still think that the support we have now is sufficient and that another crate should create a high-level wrapper of the windows console api.

**Comment by retep998** [comment]
I should point out I am starting work on a middle level wrapper of the windows console api and other console/terminal libraries can build on top of that.

https://github.com/retep998/wio-rs/blob/master/src/console.rs

**Comment by cmr** [comment]
Lovely! That looks pretty damn nice already, comparably.

**Comment by Stebalien** [comment]
I'm closing this in favour of #47 and #48.
