### ISSUE TITLE
Release for 0.3

### ISSUE THREAD

**Issue by mcasper** [Stebalien/term#51]
Any plans to release 0.3 soon? It fixes an issue that I'm experience using iron/logger, and it would be great to be able to point at an official release instead of the git url.

https://github.com/iron/logger/pull/72

Thanks for all the hard work :smile:

**Comment by Stebalien** [comment]
Sorry about the delay. I have some pretty severe breaking changes that I
want to make before releasing 0.3 but I'll push those to 0.4 if I can't
finish them by the end of the week.

**Comment by Stebalien** [comment]
I didn't get around to refactoring this week so I pushed 0.4 (I forgot that we had already done a version bump so we're skipping 0.3...). I'll push back the refactor to 0.5.

**Comment by mcasper** [comment]
Thanks!
