### ISSUE TITLE
Are there any contribution guidelines?

### ISSUE THREAD

**Issue by Thecontrarian** [Stebalien/term#52]
I'd like to contribute to the project, are there any guidelines i should be aware of first?

**Comment by Stebalien** [comment]
Only that all contributions must be dual MIT/Apache 2.0 licensed and that if I don't respond within 4 days, you should ping me.

**Comment by Stebalien** [comment]
Does this answer your question?

**Comment by Thecontrarian** [comment]
Yeah, thanks
