### ISSUE TITLE
Unimplimented terminfo capability

### ISSUE THREAD

**Issue by zcasey-starry** [Stebalien/term#89]
Hello,

When using the [prettytable-rs crate](https://crates.io/crates/prettytable-rs) with `TERM=vt100`, I got garbled output like so:
> Foo        $<2> | bar     $<2> | gorp $<2> | mumble$<2>

After some debugging, I discovered this was caused by term. In the terminfo parser ([here](https://github.com/Stebalien/term/blob/04cacee67d79ef9fe6d015567bdd24a38cd456bf/src/terminfo/parm.rs#L136)).

Specifically, it appears that term does not implement the entire specification of terminfo, from terminfo(5):
> A delay in milliseconds may appear anywhere in a string capability, enclosed in $<..> brackets, as in el=\EK$<5>, and padding characters are supplied by tputs(3X) to provide this delay.

This is used by the vt100 terminfo and can be confirmed by getting the output of `infocmp`.
I am not familiar with terminfo, but my own fix currently is the following patch:

```
--- a/src/terminfo/parm.rs
+++ b/src/terminfo/parm.rs
@@ -18,6 +18,7 @@ use std::iter::repeat;
 #[derive(Clone, Copy, PartialEq)]
 enum States {
     Nothing,
+    Ignore,
     Percent,
     SetVar,
     GetVar,
@@ -164,10 +165,18 @@ pub fn expand(cap: &[u8], params: &[Param], vars: &mut Variables) -> Result<Vec<
             Nothing => {
                 if cur == '%' {
                     state = Percent;
+                } else if cur == '$' {
+                    state = Ignore;
                 } else {
                     output.push(c);
                 }
             }
+            Ignore => {
+                old_state = Nothing;
+                if cur == '>' {
+                    state = Nothing;
+                }
+            }
             Percent => {
                 match cur {
                     '%' => {
```

This ignores the unparsed/unused feature so that my output is clean. I can submit a PR with this change, but I wanted to create an issue rather than simply submit, as I am not familiar enough with terminfo to know if this is intentionally left out, should be ignored as I am doing, or the full feature should be added.

**Comment by Stebalien** [comment]
That looks like the correct diagnosis and the correct fix. A patch would definitely be welcome.

**Comment by zcasey-starry** [comment]
I submitted a PR.
Thank you!
